description: 'phpMyAdmin app to handle the administration of MySQL over the Web.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/pma.png'
website: 'https://github.com/apioo/fusio-apps-pma'